### PR TITLE
[BUGFIX] CMake Bugfixes and permanent fix for issue #9; Illegal instruction error.

### LINKED ISSUE #9: [BUG] Illegal instruction on old x86_64 architectures, do to Tensorflow Precompiled package being compiled with AVX2 Enabled
# AVX2 Issue with Tensorflow Precompiled

Due to my limited testing coverage with fairly new computer architectures (which all have AVX2). I completely missed the possibility of someone using a computer older then 2014 on Ivy bridge era machines. 

That means that even though the machine might or might not have AVX2 optimizations available, CMake will at this moment choose the default AVX2 precompiled tensorflow package. Due to all symbols and binary code present in the binary the compiler (will and can not check) whether the hardware can run the instructions. 

## How to reproduce

Just compile it on an old machine (<2014, preferable Ivy-bridge. If your pc is newer you can also check it with QEMU).

So it compiles fine! But when running you are greeted with:

```bash
Illegal instruction (core dumped)
```

## Temporary workaround

Compile the tensorflow package from source by passing the `CLFML_FACE_DETECTOR_COMPILE_TENSORFLOW_FROM_SOURCE=ON` flag into CMake:

```bash
cmake . -DCLFML_FACE_DETECTOR_COMPILE_TENSORFLOW_FROM_SOURCE=ON -B build -G Ninja
```

## Permanent fix

I will probably fix it in the next round of optimizations by either adding a pipeline for a completely non-avx precompiled tensorflow package. Or I will add an if-statement to CMake that forces users without avx2 to always compile from source. Either way I wanted to document this, as it is a somewhat annoying bug.

### PR DESCRIPTION
**Pull request by Hoog-V**
# CMake Bugfixes and GitHub Workflow for checking if code still compiles
There were some minor mistakes in the CMakeLists that should be fixed now.

## Issue #9 bugfix
As Agit pointed out the code wouldn't run out of the box on his 2014, i5-3320M based laptop. That was due to the wrong compiler flag being entered into the Tensorflow Compilation workflow, see the fix in https://github.com/CLFML/TensorFlow_Lite_Compiled/commit/de80bcecd17a07f0b07a6271bf9bd354fb880199 commit. 

Skylake was used as compilation flag instead of Sandy Bridge, Skylake has both AVX and AVX2 meaning the compiler will compile with AVX2. Now I have set it to the older Sandy Bridge architecture which does not have AVX2. I have tested it using a Virtual Machine with AVX2 disabled. It should work now. But it would be nice if Agit could confirm.

As AVX2 has a large performance gain for supported targets, I added a check in the CMakeLists. Which checks if your host-cpu supports AVX2 and downloads the AVX2 optimized package instead of the AVX package.

## Minor Macro fixes
While working on the full gaze implementation, I stumbled up on a typo in the Model_path macro. It was prefixed with `CFML` instead of `CLFML`.

## Code compiles?

When adding more features to this library, we might encounter cases where the code doesn't compile when served in the PR. To quickly check if code compiles without having to pull and check yourself. I added a GitHub Workflow check that runs on creation of PR and automatically checks if the code compiles. If code compiles a green checkmark is presented, if not a red cross. Easy enough, right?

### CODE REVIEW

**Comment by Hoog-V** [comment]
@AgitDev-sudo Can you check if it compiles and runs with this fix (without the temporary workaround)?

**Comment by AgitDev-sudo** [comment]
> @AgitDev-sudo Can you check if it compiles and runs with this fix (without the temporary workaround)?

I'll check this in evening or tomorrow. I don't have my old laptop with me at the moment. (And probably won't use it for my project either, because now i have the "super mini pc n100"  :D )

**Comment by AgitDev-sudo** [comment]
> @AgitDev-sudo Can you check if it compiles and runs with this fix (without the temporary workaround)?

Yes, it builds (very fast, without workaround )! 
I have also run the CPU example and the ROS 2 CPU example. These also still work.

**Review by AgitDev-sudo — APPROVED** [review]

**Comment by Hoog-V** [comment]
Cool! Then I will merge!

**Pull request merged**
