### PR TITLE
[CPU Inference Only] Basic implementation of Face_Detector

### PR DESCRIPTION
**Pull request by Hoog-V**
# Basic Implementation

This PR adds a basic implementation of the Face_Detector using only CPU inference. 

## Functionality

The functionality added by this PR is;

- Detection of a single face by choosing the best classification score from the model output classifiers
- Calculating a face ROI (Region Of Interest) by creating a grid of anchors, mapping these to the model output regressors and scaling it to our input image (see anchor calculation heading)
- Basic cross-platform example code (Yes, I have tested it on Windows as well ;) )

## ROI Calculation

The BlazeFace model, which is based on the SSD (Single Shot MultiBox Detector) framework, makes extensive use of anchoring. The model outputs 896 boxes, which represent potential locations where faces might be detected. By evaluating classifier scores, we can determine which box has the highest likelihood of containing a face.

Faces are detected in one or multiple boxes that fall within a grid composed of multiple layers. In this implementation, two grids of sizes 16x16 and 8x8 are used. When overlapped, they look something like this:

output

The green grid represents the 8x8 grid.
The blue grid represents the 16x16 grid.

But you might ask, 16x16 + 8x8 = 320, which is not equal to 896, right? Yes, you're correct! To account for this, we add layers. Layers allow us to add more grid boxes at the same location, which helps increase detection accuracy by providing multiple scales and aspect ratios of anchors at each grid cell. By adding 2 layers to the 16x16 grid we get more accuracy for smaller faces and by adding 6 layers to the 8x8 grid we get more accuracy for larger faces. Which fortunately for us is the exact 896 boxes which comes out of this model ;)

To make things easier this implementation generates these anchors before inference and saves them into an array that directly maps to the model output, besides this it gives the boxes a size of 1x1 which helps with scaling it to our input image.

## Face Landmarking
I found out that it might be possible to do head pose estimation using the 6-landmarks this model outputs; See source code and [model card](https://storage.googleapis.com/mediapipe-assets/MediaPipe%20BlazeFace%20Model%20Card%20(Short%20Range).pdf). Might be interesting to implement this functionality as well.

## TPU Compatibility and Performance
In the future I want to add compatibility for the Coral Edge TPU as this will further decrease computational load. I did my best to write the code as performant as possible without relying on SIMD or anyother platform specific functionality. It got to a point where I have <1.5% CPU load (Ryzen 5 7600) and 38MB of memory usage on my Linux machine. But this can be further decreased by relying on SIMD, Edge TPU (or maybe GPU offloading, but needs more research).

## Example code
I did include some example code which builds by default when generating with CMake (only when generating in the root of this project folder, not when used as library). This demo runs on Linux, Mac and Windows and demonstrates the usage by drawing a ROI square around the face and with text in top left corner indicating whether a face has been detected.

### CODE REVIEW

**Comment by RichardKroesen** [comment]
Wow interesting, it looks clean! I also see nice things in the to-do list. And I appreciate that it should be compilable on windows ;)

**Comment by Hoog-V** [comment]
Oh and another note; Increasing camera resolution does not give you more accurate results! The model needs a 128x128 pixels frame as input. This means that your high-res image gets downscaled to 128x128 pixels to get processed by the model. 

Then the model outputs these 896 boxes which have to be scaled over your high-res image. Meaning that when you are using a high res input image the detection steps get rougher and you will certainly notice it. 

Keeping your image to something lower then 1024x768 certainly helps and gives more accurate results. (640x480 is perfectly fine as well btw)

**Review by ducroq — COMMENTED** [review]
Very neat code!
I have tested on Windows, it runs like a charm!

On Ubuntu 24, I am experiencing unexpected behavior: The camera window opens and shows the live stream with superimposed text. However, the detector seems not running.
Output:
```bash
[ WARN:0@0.603] global ./modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1 [ WARN:0@1.968] global ./modules/videoio/src/cap_gstreamer.cpp (1716) setProperty OpenCV | GStreamer warning: GStreamer: unhandled property
INFO: Initialized TensorFlow Lite runtime.
INFO: Applying 1 TensorFlow Lite delegate(s) lazily.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
VERBOSE: Replacing 164 out of 164 node(s) with delegate
(TfLiteXNNPackDelegate) node, yielding 1 partitions for the whole graph.
Note (XNNPACK): fuse Clamp Node #1 into upstream Node #0 Note (XNNPACK): fuse 
... 
Note (XNNPACK): fuse Clamp Node #79 into upstream Node #78
INFO: Successfully applied the default TensorFlow Lite delegate indexed at 0.
  *NOTE*: because a delegate has been applied, the precision of computations should be unchanged, but the exact output tensor values may have changed. If such output values are checked in your code, like in your tests etc., please consider increasing error tolerance for the check.
QSocketNotifier: Can only be used with threads started with QThread
/home/jeroen/Projects/Face_Detector.Cpp/build/face_roi_demo: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: 
undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```
Any thoughts on how to deal with this?

**Comment by Hoog-V** [comment]
This is VSCode trying to run from a sandboxed environment (snap). I see you have installed it using snap, try to uninstall vscode and install it using the [.deb installer](https://code.visualstudio.com/docs/setup/linux)

**Comment by Hoog-V** [comment]
I Have now tested it on my laptop running Ubuntu 24.04, it runs fine. Though I have vscode natively installed using the .deb installer instead of snap. When previously using the snap version, I ran into multiple issues related to path variables and other stupid things.

**Comment by ducroq** [comment]
> I Have now tested it on my laptop running Ubuntu 24.04, it runs fine. Though I have vscode natively installed using the .deb installer instead of snap. When previously using the snap version, I ran into multiple issues related to path variables and other stupid things.

yes, me too, and I wasted a good part of the morning on this :-) 
Thanks for the tip

**Comment by ducroq** [comment]
I think we could merge .
Later on I could see how to do head-pose estimation (using the landmarks).
Should I press "Merge pull request"?

**Comment by Hoog-V** [comment]
Can you first Files Changed -> Review Changes -> Approve

**Review by ducroq — APPROVED** [review]

**Comment by ducroq** [comment]
Regarding head-pose estimation: Blazeface outputs 6 approximate 2D keypoint coordinates. I have been trying to estimate head orientation from this information, but was not successful. You can have a look at the branch dedicated to this. Probably, the very crude estimator of depth is the main reason for failure.

Since we will need the face and iris landmarks anyhow (e.g. for gaze estimation and smile detection), I propose to also infer these models and compute head pose from 3D landmarks, like we did before.

**Pull request merged**
