### PR TITLE
[TPU Support] This PR adds support for the Coral Edge TPU

### PR DESCRIPTION
**Pull request by Hoog-V**
# TPU Support

Another PR, this one is for the addition of Coral TPU support. Besides the convoluted example Google gives you in their mediapipe framework, I have not found anyone who has ported the face detector to a Coral. So here are some gory details;

- Runs cross-platform and cross-architecture (Should work on Windows, Mac and Linux) (x86_64 & ARM64) (Though compiling with TPU support enabled was only tested on Linux x64 and ARM64)
- Uses the [libedgetpu library API from Google](https://github.com/google-coral/libedgetpu)
- Performance increases (Especially on ARM, of almost 300%)
- Can (for now) only be used with a single edge tpu connected to the system, if multiple edge tpu's are connected to the system it will now always pick the first one, without checking if it is being used! 

## What has been added?
Mainly code that sets-up the delegate, not much else. There was one implementation detail which differed between the TPU and CPU model. That was that the input image for the TPU model has to be 8-bit 3-channels encoded, the CPU model requires 32-bit Floating point 3-bit channels encoded input images. So I had to account for this by removing the conversion to the 32-bit Floating point 3-bit code, as by default videostreamer (and most video sources) give 8-bit 3-channels encoded images.

### CMake build option
Edge TPU support should not build by default, as that would create a direct dependency on the libedgetpu library. Probably a substantial amount of users of this library will not use a Coral edge TPU anyway.

To circumvent creation of direct dependency on libedgetpu, a CMake option was added which voluntarily adds coral support to the library using Macro's generated during CMake configure run. These macro's then comment/uncomment sections of code related to the Coral TPU.

You can now compile it by adding the `-DFACE_DETECTOR_ENABLE_CORAL_TPU=ON` argument to the CMake configure command;

```cmake
cmake . -B build -G Ninja -DFACE_DETECTOR_ENABLE_CORAL_TPU=ON
```
or by adding this to your settings.json in vscode:

```json
"cmake.configureSettings": {
    "FACE_DETECTOR_ENABLE_CORAL_TPU": "ON"
}
```

### Example
This macro has also been added to the example code which enables the TPU in the example code by default when compiling with CMake TPU support enabled. 

### Readme updated
The Readme has been updated with some simple steps on how to compile the code with TPU support. This does assume that you have all the prerequisite libraries installed on your system.

## Benchmarks
On my PC:
| Without TPU  | With TPU  |
|---|---|
|  3% CPU Util  | 0.95% CPU Util  |

On a RPI (Yes went through the pain to cross-compile libedgetpu to Raspberry Pi 4 (took some hours to compile (as I didn't have a 8-GB RPI, fricking bazel :/))
| Without TPU | With TPU |
|---|---|
|  33% CPU Util | 12% CPU Util  |

So yes we got 200-300% performance increases by offloading the model inference to the TPU. I count that as a massive win for compute-limited applications, such as running running it on a Raspberry Pi.

## What could be improved
- libedgetpu is annoying to compile, it would be useful to include it somewhere as precompiled libraries. This massively saves time and makes sure we got a version that matches the version of Tensorflow used in this library. **Yes these have to be version matched** ;(
- Add some documentation on how to set-up on the various platforms/oses (Windows, Mac and Linux)
- Add support for choosing between multiple edge-tpu's

### CODE REVIEW

**Comment by ducroq** [comment]
This looks very interesting. Unfortunately, I don't have a Coral TPU available, so hard to test right now. Or do we have one installed in the edge server?
Is it feasible to implement a cross-compilation pipeline for libedgetpu using CI/CD runners on GitHub Actions (or GitLab CI/CD), considering the specific build dependencies and target architecture requirements? In that way we could have precompiled libs available for download.

**Comment by ducroq** [comment]
In the demo you have a general switch for FACE_DETECTOR_ENABLE_CORAL_SUPPORT, but also one in the main. Is that required, I would prefer to have only one switch?

**Comment by ducroq** [comment]
I am wondering: The TPU model uses 8-bit channels, which makes sense given we are dealing with ordinary camera frames. Is it known if the model itself is quantized? 
The CPU model uses 32-bit floating point, which could imply that the model is not quantized, and a higher precision is pursued. 
Are both models comparable in terms of precision and performance?

**Comment by Hoog-V** [comment]
> I am wondering: The TPU model uses 8-bit channels, which makes sense given we are dealing with ordinary camera frames. Is it known if the model itself is quantized? 
> The CPU model uses 32-bit floating point, which could imply that the model is not quantized, and a higher precision is pursued. 
> Are both models comparable in terms of precision and performance?

You're right, I forgot to mention that the model is indeed quantized. It is 8-bit quantized otherwise it can't run on a TPU. It does have impact on the accuracy. 

From my limited testing I have noticed that it gave a bit more false positives (especially with bad lighting conditions, although it does not seem to have false negatives). This can be probably mitigated partly by adjusting the threshold to something higher.

**Comment by Hoog-V** [comment]
> In the demo you have a general switch for FACE_DETECTOR_ENABLE_CORAL_SUPPORT, but also one in the main. Is that required, I would prefer to have only one switch?

I am gonna change this in next commit

**Comment by Hoog-V** [comment]
> This looks very interesting. Unfortunately, I don't have a Coral TPU available, so hard to test right now. Or do we have one installed in the edge server?
> Is it feasible to implement a cross-compilation pipeline for libedgetpu using CI/CD runners on GitHub Actions (or GitLab CI/CD), considering the specific build dependencies and target architecture requirements? In that way we could have precompiled libs available for download. 
> 

There is no coral tpu installed in the edge server (budget cuts ;) ). I do really recommend to buy the m2 b+m key, as these only cost 25€ and can be installed in the ssd slot of most computers nowaday. (Or the m2 a+e key to put in wifi slot of pc (check first if your pc has this!)). By going the USB route you can't go wrong either, as it is supported by any pc newer > 2008 with usb 3.0 (€75), but is more expensive.

GitHub runners might be feasible, going to try it in the future.

**Comment by ducroq** [comment]
> > I am wondering: The TPU model uses 8-bit channels, which makes sense given we are dealing with ordinary camera frames. Is it known if the model itself is quantized?
> > The CPU model uses 32-bit floating point, which could imply that the model is not quantized, and a higher precision is pursued.
> > Are both models comparable in terms of precision and performance?
> 
> You're right, I forgot to mention that the model is indeed quantized. It is 8-bit quantized otherwise it can't run on a TPU. It does have impact on the accuracy.
> 
> From my limited testing I have noticed that it gave a bit more false positives (especially with bad lighting conditions, although it does not seem to have false negatives). This can be probably mitigated partly by adjusting the threshold to something higher.

In that case it wouldn't it make more sense to compare the performance of a quantized CPU model to the TPU model? If that is available at least, wouldn't take the effort the quantize yourself :-)

**Review by ducroq — APPROVED** [review]

**Pull request merged**
